version: '3'

services:
  bot:
    image: avrae
    build:
      context: .
      args:
        ENVIRONMENT: production
    env_file:
      - ./docker/env
    environment:
      ENVIRONMENT: production
    network_mode: host
